# Generated by Django 3.2 on 2023-04-25 15:18

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArticleName', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardValue', models.CharField(max_length=200)),
                ('ArticleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='Translated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convertedText', models.CharField(max_length=300)),
                ('pronouncedText', models.CharField(max_length=300)),
                ('lang', models.CharField(max_length=40)),
                ('audio_link', models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='audio-dump/')),
                ('cardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans', to='articles.card')),
            ],
        ),
    ]
